### ISSUE TITLE
iteritems is only valid for Python 2, breaking Python 3

### ISSUE THREAD

**Issue by robbiet480** [Danielhiversen/flux_led#14]
There's two `iteritems` in the code:

- [here](https://github.com/Danielhiversen/flux_led/blob/master/flux_led/__init__.py#L202)
- [here](https://github.com/Danielhiversen/flux_led/blob/master/flux_led/__init__.py#L223)

Having these means this library is not fully Python 3 compatible. I'd suggest someone fix it some time so that this library would then be Python 3 compatible.

**Comment by tchellomello** [comment]
https://github.com/Danielhiversen/flux_led/blob/master/flux_led/__main__.py#L202

https://github.com/Danielhiversen/flux_led/blob/master/flux_led/__main__.py#L223

**Comment by tchellomello** [comment]
This was fixed by https://github.com/Danielhiversen/flux_led/pull/26

Closing
