### ISSUE TITLE
Automatically identify LEDENET devices

### ISSUE THREAD

**Issue by mjg59** [Danielhiversen/flux_led#22]
The second byte of the state string determines the type of device and the protocol it speaks. Do you have any dumps of that for the LEDENET systems? I've been figuring out how to use this to determine whether a device is RGB+W or true RGBW as well.

**Comment by mjg59** [comment]
@bah2830 Looks like you may have some of this hardware?

**Comment by bah2830** [comment]
@mjg59 Yes the Ledenet controller I use with this supports true RGBWW with all 5 channels. However my testing of it was using just standard RGB (3 channel) and RGBW (4 channel) strips and not in the RGBWW mode

**Comment by mjg59** [comment]
@bah2830 are you able to provide the bytes returned by the refreshState command on your devices?

**Comment by robbiet480** [comment]
@mjg59 Which product do you have? I just got [this](https://www.amazon.com/gp/product/B01LW2POQR/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1) which I am planning to flash with [this](https://github.com/mertenats/Arilux_AL-LC03) once I have access to my soldering iron again.

Anyway, mine is RGBW but does not properly function with the LEDENET protocol set even though it appears to be version 3.

**Comment by mjg59** [comment]
@robbiet480 I have the RGB version of that, along with an RGBW UFO (https://www.amazon.com/LEDENET-Controller-Android-Smartphone-Control/dp/B00MDKOSN0) and an RGBWW/CW (https://www.amazon.com/gp/product/B01AA6221S/ref=oh_aui_detailpage_o08_s03?ie=UTF8&psc=1). Having the response to the refreshState command from your RGBW controller would also be helpful.

**Comment by robbiet480** [comment]
Getting `None` when running this:

```python
import flux_led
bulb = flux_led.WifiLedBulb('192.168.1.43')
bulb.turnOn()
bulb.refreshState()
```

**Comment by robbiet480** [comment]
@mjg59 Unsure if this is what you were looking for but...

`bytearray(b'0\x81\x04#a \x15\x00\x00\xff\x00\x03\x00Z')`

**Comment by mjg59** [comment]
Ok, interesting, that seems to show with the same ID as the UFO controller I have. I'll try to play around a little tonight.

**Comment by robbiet480** [comment]
@mjg59 If you want to borrow one of my extra controllers I live in downtown Oakland (Grand & Broadway)

**Comment by mjg59** [comment]
Ok yeah what's defined as the LEDENET protocol here isn't what these devices speak. I can easily add support for these ones, but I really need to see the output from one of the devices that the LEDENET code was written for so I can figure out what's supposed to be happening here.

**Comment by mjg59** [comment]
@robbiet480 Can you check whether https://github.com/Danielhiversen/flux_led/pull/23 works with your device? @bah2830 can you see whether this works with yours without having to manually set the LEDENET protocol? If not, can you run -i and provide the raw state information?

**Comment by robbiet480** [comment]
Testing now, will get back to you shortly

**Comment by robbiet480** [comment]
Yes #23 works with my device.

**Comment by robbiet480** [comment]
btw, `-i` prints this:

> Unknown ID [192.168.1.43] ON  [Color: (255, 0, 0) raw state: 129,4,35,97,32,21,255,0,0,0,3,0,90,154,]

**Comment by mjg59** [comment]
Nice. I *hope* I've also figured out the device IDs that need the 8-byte protocol, but we'll wait for confirmation from @bah2830.

**Comment by outrun0506** [comment]
He Guys,

i also own the UFO-Controller mentioned above. If there is a testing i could do, please let me know

BR

Lukas

**Comment by mjg59** [comment]
@outrun0506 Is commenting out the msg.append(int(w)) the only thing you did? What does -i give you for the raw state? If the UFO is the same as mine it should be giving an id of 129 (ie, 0x81), and that shouldn't be setting the LEDENET protocol. Are you manually setting the protocol yourself?

**Comment by outrun0506** [comment]
@mjg59 
-i gives me following 

`Unknown ID [192.168.0.73] ON  [Color: (255, 255, 0) Brightness: 255 raw state: 129,4,35,97,33,16,255,255,0,0,3,0,0,59,]`

Just to clarify -  flux_led is working from the commaline like a charme. I implement the code also to HomeAssistant, and there it is not working without my changes. Maybe i should wait, until the new flux_led is implemented as new component.

**Comment by mjg59** [comment]
@outrun0506 Ok cool - those changes should also be unnecessary, since having a state ID of 129 (ie, 0x81) should set self.rgbwprotocol which should then skip that code.
