### ISSUE TITLE
Hao Deng Mesh Downlight Support

### ISSUE THREAD

**Issue by libby2cm** [Danielhiversen/flux_led#356]
I recently picked up some Zengge/HaoDeng/MagicHome/MagicHue (who's to say..) recess downlights, which are BLE mesh, and have a gateway.  I've gone down a number of rabbit holes, but this component seems most promising, but it won't connect to the gateway locally.  I can telnet to it on port 5577 though.  Might be a case of the plugin always expecting a single light where technically these would present as an array of 1 or more of them when backhauled over the mesh.

https://www.amazon.com/gp/product/B0974P1459/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&th=1

My other thought was to try and create a ble/wifi bridge on esphome, but that will not be fun.

tks

**Comment by bdraco** [comment]
We previously talked with Zengee's support and they confirmed there isn't a local control option for the bridges.  The bridges speak MQTT to their servers so you might be able to reconfigure it to speak to an MQTT server locally, however we haven't been able to get that to work.

**Comment by libby2cm** [comment]
Thanks, I ended up just returning them and getting another brand that run tuya.  I didn't like the thought of my lighting being effectively 'licensed' by the whims of a rando vendor either.  Tuya probably isn't much better in that regard, but at least there will be more mad people if something happens :)  I can try to tazmota them too i suppose.
