### ISSUE TITLE
Color and White LED at same time

### ISSUE THREAD

**Issue by ich77** [Danielhiversen/flux_led#39]
Hallo,

is it possible to turn on wihte and color LED at same time?

Thanks 

Markus

**Comment by Danielhiversen** [comment]
Depends on your bulb.
Unfortunately the code is the only documentation: https://github.com/Danielhiversen/flux_led/blob/master/flux_led/__main__.py

**Comment by solomonj1963** [comment]
Took me a couple days, but found that you can RGBW "quadruplet" with -c option.  To get full white as bright as possible from my RGBWW's, I use flux_led.py -sS -c 255,255,255,255 -1.  It was that simple.  No need to use the -w option.
