### ISSUE TITLE
Devices appear off when turned on and don't react to commands

### ISSUE THREAD

**Issue by Nezz** [Danielhiversen/flux_led#395]
Since updating to HA 2023.8 I have issues with my Magic Home RGBCCT wifi led controllers (AK001-ZJ2101, firmware 1.06).  I have 4 of them and they all misbehave since the update:
1. When turned on, they turn on with the last color and brightness instead of the one I requested
2. After being turned on, they report that they have turned off, but they are actually turned on:
![image](https://github.com/Danielhiversen/flux_led/assets/431167/0a8c5495-c149-4d17-9ebe-9051739d3b35)
![image](https://github.com/Danielhiversen/flux_led/assets/431167/8c15f825-5616-4c9b-a125-dc12d0839f70)
3. Once turned on commands to change the color or brightness don't work.
4. Turning the devices off works correctly

Changing the color or brightness is only possible after the device has been turned on but before HA reports that it's off. Therefore chaging the color now requires three steps:
1. Turn off
2. Turn on
3. Set color

I checked the behaviour with the native app using local control and the device indeed reports that it's turned off after it was turned on via HA. However, if I disable the HA integration then they behave correctly in the Magic Home app.

Relevant error logs:
![image](https://github.com/Danielhiversen/flux_led/assets/431167/a5bc7284-597f-459a-a5ee-888985232b69)

**Comment by bdraco** [comment]
Please open an issue on the core report with debug logs and diagnostics.

**Comment by bdraco** [comment]
Likely could be either either 

- the device is listed wrong in models_db and needs the two step 

Or

- https://github.com/Danielhiversen/flux_led/pull/393 sped things up enough that the two stage turn on process is now too fast and the device has a race bug which misses the second command

**Comment by bdraco** [comment]
Impossible to tell which issue it is without logs and diagnostics though

**Comment by Nezz** [comment]
Thanks, I have reported it with logs.

**Comment by bdraco** [comment]
thanks closing in favor of https://github.com/home-assistant/core/issues/98310
