### ISSUE TITLE
Does this work with other controllers?

### ISSUE THREAD

**Issue by koma85** [Danielhiversen/flux_led#4]
Does this work on other controllers?
I've found a number of Led Strip controller that claim to work with the app Magic Home like those:
https://www.amazon.it/Regolatore-Wireless-striscia-regolatore-Smartphone/dp/B01J5A5YYM/ref=sr_1_4?s=kitchen&ie=UTF8&qid=1472830801&sr=1-4&keywords=led+controller

Have you tried?

**Comment by tchellomello** [comment]
Hello @koma85, I did not tested yet but it seems it is the same chipset and controller so it should work.

**Comment by koma85** [comment]
Flawless. Thank you
