### ISSUE TITLE
5 channel RGBWW controller support; header 0x8125

### ISSUE THREAD

**Issue by claudobahn** [Danielhiversen/flux_led#44]
@gerth2 and I have a controller that uses a variation of the LEDENET controller: https://www.amazon.com/gp/product/B01DY56N8U/

We've had some discussions over in this WIP PR: https://github.com/Danielhiversen/flux_led/pull/42

Basically, we both get packets from the controller that look like this (14 bytes):

> 81 25 23 61 21 06 38 05 06 f9 01 00 0f 9d
0 Unknown
1 Type?
2 On/Off (23/24)
3 Effect
4 Unknown
5 Speed
6 Red
7 Green
8 Blue
9 Warm White
10 Unknown (always 01 so far)
11 Cold White
12 White/Color mode (f0 when colors were set, 0f when whites were set)
13 Checksum (I think?)

The Magic Color app sends packets that look like this (9 bytes):

> 31 bc c1 ff 00 00 f0 0f ac
> 31 00 00 00 d9 8a 0f 0f b2
0 Command
1 Red
2 Green
3 Blue
4 Warm White
5 Cold White
6 Write mode (f0 for color, 0f for white) -- should try ff to see if both can be written
7 Unknown
8 Checksum

@mjg59 you may be interested in the details here, as it seems related to #22 although with a different protocol variation.

Edit: corrected white/color mode byte meaning in status packet

**Comment by mjg59** [comment]
Your device looks identical to the one I wrote this code against, but it may well have different firmware. I'll try to take a look this weekend. I should really have documented dumps for each of the types I have to make this easier :(

**Comment by claudobahn** [comment]
@mjg59 do you know if any of the packet captures had WW and CW, but no write mode (e.g. f0 / 0f)?

**Comment by claudobahn** [comment]
Hm, looking through the history, it seems that up until PR #37 things were probably fine. Seems like that PR re-interpreted the LEDENET protocol and combined stuff into the "special" byte, which is what's causing issues.

So the guess I'm trying to validate is that there aren't actually any devices that have 2 white channels but don't include a 0f/f0/00 after the second white channel. Basically I think the 8-byte protocol doesn't do cold white. I'm hoping only the 9-byte protocol has cold white :)

Maybe that pull request made that change accidentally? Since it really seems to be unrelated to this type of controller.. Hoping @mjg59 can provide more insight.

**Comment by mjg59** [comment]
Ah, that would explain it. Ok, let me dig out some stuff and test this.

**Comment by zapedge** [comment]
so how can i get homeassistant to work with all 5 channels?
