### ISSUE TITLE
Add output channel remap ability

### ISSUE THREAD

**Issue by gerth2** [Danielhiversen/flux_led#45]
There seems to be some discrepancies between different LED strip manufacturers on what color wires mean what, or which bytes control which output channels.

To minimize confusing wiring or electrical work, support the ability to remap output channels per-device. Once the mapping is determined for the device, interacting with the flux_led API should be able to cause colors to change correctly (ie, setting the red channel value in the API causes the red LED's to turn on on the strip).

**Comment by claudobahn** [comment]
What's labeled on your controller? Mine has:
V-, V+, V+, R, G, B, WW, CW

and that properly corresponds to what the software does.

However, the RGB strips I have use:
V+, G, R, B, W

So perhaps what you're running into is not a mislabel on the controller, but rather a mismatch of arrangement between the controller and strip.

Since these controllers have screw terminals, you just have to switch R/G.

**Comment by gerth2** [comment]
Two cases
  1. for the [LEDNET](https://www.amazon.com/gp/product/B01DY56N8U/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1) controller we have, I have the same label as you do - and I confirmed with a meter that turning on the Red channel actually causes the Red output to have 12V (W/R/T V+). However, the LED strip connected is mislabeled - applying +12V and then grounding the red wire (and pad labeled R) actually causes the green LED's to turn on. I have currently remedyed this with the method you suggested, swapping the screw terminals for R and G.

  2. I have a second  [controller](https://www.amazon.com/gp/product/B01JZ2SI6Q/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1) & [strip](https://www.amazon.com/gp/product/B01FHA5R1E/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1) which have the same connector, but blue and green are swapped. In this case, the pad labels on the strip are correct, but the labels on the output of the controller are incorrect (confirmed with meter again).

Thinking through this more, in case 1 the right answer is probably to simply switch terminals, and label the wires properly. 

For case 2, there's either a software fix, or I could re-do the labels and wiring to match. 

I definitely wouldn't call this crucial functionality....and definitely thinking about it now, it's arguable whether it's the right way to solve it or not.  So far, I have a sample size of 1 to say controllers don't always have the right RGB mapping at their outputs (per the label on the controller).
