### ISSUE TITLE
Can't set colors or brightness 

### ISSUE THREAD

**Issue by quadflight** [Danielhiversen/flux_led#47]
Using Ledenet strip module. Only the functions/animations, on off works but not set color
Any help would be greatly appreciated

**Comment by Danielhiversen** [comment]
Have you tried to change the protocol?
https://github.com/Danielhiversen/flux_led/blob/master/flux_led/__main__.py#L779

Your lights might not be supported.

**Comment by w1ll1am23** [comment]
I am having this same issue. My lights use to work awhile back and now I am no longer able to change color. I can do whatever troubleshooting is required to figure this out.

**Comment by Danielhiversen** [comment]
You need to provide more info. 
What function are you calling? Are you getting any errors?

**Comment by w1ll1am23** [comment]
I can turn on/off, and select an effect. Color and brightness do not work. This is the output of the color change command.

```
(hass_dev) w1ll1am@w1ll1am:~$ flux_led 192.168.5.53 --on
Turning on bulb at 192.168.5.53
(hass_dev) w1ll1am@w1ll1am:~$ flux_led 192.168.5.53 -c 255,0,0
Setting color RGB:(255, 0, 0)
[(255, 0, 0)]
```

**Comment by quadflight** [comment]
Same as previous issue. Ledenet V1. Tried setting protocol as well. Turning on/off and functions work just fine.
