### ISSUE TITLE
How to increase/decrease brightness of color apart from warm white and cold white

### ISSUE THREAD

**Issue by Gowthammahadevaiah** [Danielhiversen/flux_led#48]
Hi, 
I want to increase/decrease the brightness of every color. But, I can able to perform it on warm/cold white color. 
How to achieve this?

**Comment by Danielhiversen** [comment]
Have you tried the `brightness` parameter in `setRgbw`?
https://github.com/Danielhiversen/flux_led/blob/master/flux_led/__main__.py#L865
