### ISSUE TITLE
RuntimeWarning: Wrong order of execution?

### ISSUE THREAD

**Issue by filipre** [Danielhiversen/flux_led#56]
Hi, 

if I issue any `python -m flux_led ...` command, I receive the following runtime warning:

```
/Users/rene/miniconda3/lib/python3.6/runpy.py:125: RuntimeWarning: 'flux_led.__main__' found in sys.modules after import of package 'flux_led', but prior to execution of 'flux_led.__main__'; this may result in unpredictable behaviour
``` 

The commands run fine on the device but I wonder whether this warning could turn into a bug at some point.

Greetings
René

**Comment by ekendra-nz** [comment]
Same 

`RuntimeWarning: 'flux_led.__main__' found in sys.modules after import of package 'flux_led', but prior to execution of 'flux_led.__main__'; this may result in unpredictable behaviour
`   

Seems like a deal-breaker to me.

**Comment by ekendra-nz** [comment]
Workaround if using os module to execute CLI from a script:

put this before **import flux_led**

```
import os, warnings
warnings.simplefilter("ignore") 
os.environ["PYTHONWARNINGS"] = "ignore" 

```
