### ISSUE TITLE
Use non-zero exit code if command fails? 

### ISSUE THREAD

**Issue by alc6379** [Danielhiversen/flux_led#60]
Hi there, 

Love the project, awesome work. 

I just have one request: I might be able to do it if I have time to go through the code, but I have a set of lights that don't connect consistently to my wifi. If I use flux_led via bash in Linux, I'll have errors, like 

`Unable to connect to bulb at [redacted_ip]: bytearray index out of range`

or 

`Unable to connect to bulb at [10.0.0.16]: timed out`

...Which, if my strip isn't available, makes sense. 

That's an error condition-- I realize that the script loops through bulbs to try and set them all, but the sys.exit(0) at the end doesn't give an indication to a shell script that there may have been errors based on the exit code. 

Would you be willing to change this, or would you accept a pull request?

**Comment by Danielhiversen** [comment]
Yes, please open a pull request
