### ISSUE TITLE
Support for MagicLight v7 RGBCW bulbs

### ISSUE THREAD

**Issue by skylord123** [Danielhiversen/flux_led#61]
I bought these exact bulbs and color control doesn't seem to be working with it in Home Assistant:
https://www.amazon.com/gp/product/B07VQLZBNW/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

The bulbs display their model number as v7 inside the MagicLight Android app (which is interesting because some older bulbs I purchased that only support rgb show as v8 and work fine).

Setting the color temperature (CCT) from inside the Android app gets the light to use brighter LEDs whereas if you select a color it uses LEDs that aren't nearly as powerful. If the bulb is setup in HA with the mode as `rgbw` it allows you to control the color temperature but not the color. Even though you can change the color temperature it is very buggy and often times will just turn the bulb off.

These bulbs are incredibly cheap and when using the brighter white LEDs the bulb is actually pretty bright. The main reason I purchased them was to setup some cheap outdoor color bulbs for Christmas/Holiday lighting. I have Hue but $50 per bulb for outdoor color lighting is just too much. At this price point I wouldn't mind buying more bulbs if support was added for them.

If someone needs a bulb to help get this done I would be willing to buy and ship one if it is within the mainland USA.

**Comment by skylord123** [comment]
Someone else has requested this on the Home Assistant issues:
https://github.com/home-assistant/home-assistant/issues/28940

**Comment by skylord123** [comment]
I don't know if this helps but I found this post under the Hubitat forum that looks like they have RGBCW support:
https://community.hubitat.com/t/release-magic-home-wifi-devices-0-89/5197
and a link to their source github file for this support:
https://github.com/adamkempenich/hubitat/blob/master/Drivers/MagicHome/MagicHome%20Wifi%20%E2%80%94%20Controller%20(RGBWW).groovy

I hope this is helpful in adding RGBCW support.

**Comment by skylord123** [comment]
I downloaded the module onto my laptop and ran it manually and it actually looks like it is working just fine. It seems that bug I am having is something to do with Home Assistant's use of this library.

I'm going to leave this open for now just-in-case.

**Comment by skylord123** [comment]
I ran some more tests by setting various settings on the bulb from the app and seeing what the status of the bulb was between each command. Looks like the brightness isn't detected correctly with this bulb:

```
$ python3 -m flux_led 192.168.1.199 --warmwhite 10
Setting warm white mode, level: 10%
$ python3 -m flux_led 192.168.1.199 -i
Unknown ID [192.168.1.199] ON  [Warm White: 9% raw state: 129,53,35,97,1,1,0,0,0,25,7,25,15,132,]

$ python3 -m flux_led 192.168.1.199 --warmwhite 100
Setting warm white mode, level: 10%
$ python3 -m flux_led 192.168.1.199 -i
Unknown ID [192.168.1.199] ON  [Warm White: 100% raw state: 129,53,35,97,1,1,0,0,0,255,7,255,15,80,]

$ python3 -m flux_led 192.168.1.199 --coldwhite 100
Setting cold white mode, level: 100%
$ python3 -m flux_led 192.168.1.199 -i
Unknown ID [192.168.1.199] ON  [Color: (0, 0, 0) Brightness: 0 raw state: 129,53,35,97,1,1,0,0,0,0,7,255,15,81,]

$ python3 -m flux_led 192.168.1.199 --coldwhite 10
Setting cold white mode, level: 10%
$ python3 -m flux_led 192.168.1.199 -i
Unknown ID [192.168.1.199] ON  [Color: (0, 0, 0) Brightness: 0 raw state: 129,53,35,97,1,1,0,0,0,0,7,25,15,107,]

$ python3 -m flux_led 192.168.1.199 -c 255,0,0 # red
Setting color RGB:(255, 0, 0)
[(255, 0, 0)]
$ python3 -m flux_led 192.168.1.199 -i
Unknown ID [192.168.1.199] ON  [Color: (255, 0, 0) Brightness: 255 raw state: 129,53,35,97,1,1,255,0,0,0,7,0,240,50,]

$ python3 -m flux_led 192.168.1.199 -c 0,255,0 # blue
Setting color RGB:(0, 255, 0)
[(0, 255, 0)]
$ python3 -m flux_led 192.168.1.199 -i
Unknown ID [192.168.1.199] ON  [Color: (0, 255, 0) Brightness: 255 raw state: 129,53,35,97,1,1,0,255,0,0,7,0,240,50,]

$ python3 -m flux_led 192.168.1.199 -c 0,0,255 # green
Setting color RGB:(0, 0, 255)
[(0, 0, 255)]
$ python3 -m flux_led 192.168.1.199 -i
Unknown ID [192.168.1.199] ON  [Color: (0, 0, 255) Brightness: 255 raw state: 129,53,35,97,1,1,0,0,255,0,7,0,240,50,]
```

I may be using the wrong options and will test some others later. It is possible this bulb's data format may need to be added. I hope this raw state information is helpful.

**Comment by skylord123** [comment]
Warmwhite and coldwhite isn't being handled correctly by flux_led. If you set warm white the raw data shows it actually set both warmwhite (ww) and coldwhite (cw). This means you cannot actually get the light to the warmest light level because it will always be turning on the coldwhite leds along with the warmwhite leds. ww and cw need to be able to be handled independently for this bulb.

Here is the snippet from the above log that proves that:
```
$ python3 -m flux_led 192.168.1.199 --warmwhite 10
Setting warm white mode, level: 10%
$ python3 -m flux_led 192.168.1.199 -i
Unknown ID [192.168.1.199] ON  [Warm White: 9% raw state: 129,53,35,97,1,1,0,0,0,25,7,25,15,132,]

$ python3 -m flux_led 192.168.1.199 --warmwhite 100
Setting warm white mode, level: 10%
$ python3 -m flux_led 192.168.1.199 -i
Unknown ID [192.168.1.199] ON  [Warm White: 100% raw state: 129,53,35,97,1,1,0,0,0,255,7,255,15,80,]
```
Look at the raw state for both of them. index 9 and 11 in the raw data are what control cw and ww respectively. You can see that it is setting a value in both for these calls when it should only be setting it in the first one. If you set it to warm white from the Android app and check the values you get this:

```
$ python3 -m flux_led 192.168.1.199 -i
Unknown ID [192.168.1.199] ON  [Warm White: 100% raw state: 129,53,35,97,1,1,0,0,0,255,7,0,15,27,]
```
Which shows that only `255` is only being set on the warmwhite channel and 0 is being sent to the coldwhite channel (and the light looks much warmer).

If I do the inverse and set it to cold white from the android app I get this when checking the info:
```
Unknown ID [192.168.1.199] ON  [Color: (0, 0, 0) Brightness: 0 raw state: 129,53,35,97,1,1,0,0,0,0,7,255,15,81,]
```
Which displays the brightness as 0 even though it is actually full brightness on cold white.

It basically looks like the coldwhite and warmwhite channels are being handled incorrectly.

@Danielhiversen should another mode called `rgbcw` or something else be added to handle these changes? I am trying to figure out and see if I can get a patch for this but I don't want to break things for other people's bulbs.

**Comment by adamkempenich** [comment]
Hi, SkyLord! Just saw your comment about my driver in HE. Around a year ago, I'd implemented WW/CW on RGBCCT Controllers and Bulbs in HASS, but ended up feeling discouraged with how it should be implemented. If you'd like, I'd be willing to help you work through whatever methods you feel would be best to implement.

**Comment by leifclaesson** [comment]
@skylord123 @Danielhiversen I have fixed the warm white/cold white bug in my own fork and created a pull request. https://github.com/Danielhiversen/flux_led/pull/64
https://github.com/leifclaesson/flux_led
