### ISSUE TITLE
Feature Request: Adding support for IC-Controllers

### ISSUE THREAD

**Issue by Jonasn97** [Danielhiversen/flux_led#68]
Hey,
any plans on adding the possibility to add those IC-Controllers or any advice on how to implement them myself?
https://www.ebay.de/itm/Wifi-RGB-IC-Led-Kontroller-Controller-Fernbedienung-fur-Android-IOS-Echo-Alexa/224136454002
Thanks
Jonas :)

**Comment by bdraco** [comment]
This was implemented
