### ISSUE TITLE
Cold white mode not properly supported on newer bulbs

### ISSUE THREAD

**Issue by ywwg** [Danielhiversen/flux_led#69]
This encompasses two issues: warm white mode isn't set correctly, and there is a new bulb type hex value.

comment says:

```
# LEDENET devices support two white outputs for cold and warm. We set
# the second one here - if we're only setting a single white value,
# we set the second output to be the same as the first
```

This doesn't seem like the right thing to do, because on my newer bulbs it causes both the warm and cold lights to be activated at the same time, resulting in a not-warm appearance.  Simply appending 00 fixes the issue. 

The new bulb type is 0x35.  Example messages: `8135236101050000000007ff0f55`

I'm making a PR for these issues

**Comment by oblitum** [comment]
I confirm this, and your PR allows for dimmer warm light.
