### ISSUE TITLE
Distinguish RGB and RGBW LED Controllers

### ISSUE THREAD

**Issue by mbahmani90** [Danielhiversen/flux_led#76]
Hello Dear.

I have RGB and RGBW led controller and i want to distinguish these two type of LEDs.

Is there any command that determined whether the led is RGB or RGBW?

Thank you.

**Comment by icemanch** [comment]
> Hello Dear.
> 
> I have RGB and RGBW led controller and i want to distinguish these two type of LEDs.
> 
> Is there any command that determined whether the led is RGB or RGBW?
> 
> Thank you.

It should now tell you which type it is when you run flux_led -sSti

**Comment by mbahmani90** [comment]
I have to extract LED type by sending data from a micro controller. Therefore, i can not use python. the information that i received from led controller is as follows:

192.168.1.35,DC4F22C160FA,AK001-ZJ200

Is it possible to detect LED type from this Information.

Thank you.

**Comment by icemanch** [comment]
> I have to extract LED type by sending data from a micro controller. Therefore, i can not use python. the information that i received from led controller is as follows:
> 
> 192.168.1.35,DC4F22C160FA,AK001-ZJ200
> 
> Is it possible to detect LED type from this Information.
> 
> Thank you.

Not sure if I can help. You've opened an issue on Python code that you're not using.  I have no way to debug the project you're working on.  It does seem that the message is incorrect but, most of that work was done by others and I don't actually know what the raw message look like.

You can find the API here https://westwingx.leadpages.co/flux-developer/
