### ISSUE TITLE
Release to pypi

### ISSUE THREAD

**Issue by sebr** [Danielhiversen/flux_led#77]
Hi!
Can you please release v 0.2.3 of `flux_led` to pypi?

Thanks!

**Comment by icemanch** [comment]
Yes,  pypi will get updated over the weekend.

**Comment by sebr** [comment]
@Danielhiversen ping, any chance you can get this done? Many thanks 😃

**Comment by Danielhiversen** [comment]
Ahh, I thought it was done.
I see now that it failed since the travis integration is broken

**Comment by Danielhiversen** [comment]
0.23.1 released
