### ISSUE TITLE
Compatibility with Home Assistant

### ISSUE THREAD

**Issue by a-waider** [Danielhiversen/flux_led#78]
Hi there,

is this implementation compatible to integrate it into Home Assistant?

**Comment by icemanch** [comment]
It was a while ago but, I need to double check before I say yes.  I've been disconnected for a month or two now.  I'm reviewing this weekend to see what needs to be done.

**Comment by icemanch** [comment]
> Hi there,
> 
> is this implementation compatible to integrate it into Home Assistant?

IT is.  Older versions are being used in the component "flux_led" but, there's work being done to use the latest version which fixes some bugs.
