### ISSUE TITLE
Add RGBCW Light control?

### ISSUE THREAD

**Issue by Zaacis** [Danielhiversen/flux_led#79]
Hi,

This doesn't support my RGBCW lights and I wanted to see if it could with some a minor adjustments. A fix may be near line 700 where the mode code for this light responds as 01, interpreted as WW in the comments. It looks a little different in the code however at line 601 where 01 actually registers as DIM and not RGBM. I am curious if then before making a 01 device register as a WW or DIM? light if we could run another conditional to see if it could recognize something closer to a RGBW controller - that might be all it takes to get this working for an RGBCW light.

I have a mockup at home in C# and know the commands well.

Here is an example response from the Magic Light RGBCW device:
RGBCW
`#    81 35 24 61 01 05 FE 00 00 00 07 00 0F 55`
(this is my RGBCW device response)

```
#     81 25 23 61 21 06 38 05 06 f9 01 00 0f 9d
#     |  |  |  |  |  |  |  |  |  |  |  |  |  |
#     |  |  |  |  |  |  |  |  |  |  |  |  |  checksum
#     |  |  |  |  |  |  |  |  |  |  |  |  color mode (f0 colors were set, 0f whites, 00 all were set)
#     |  |  |  |  |  |  |  |  |  |  |  cool-white  0x00 to 0xFF
#     |  |  |  |  |  |  |  |  |  |  version number
#     |  |  |  |  |  |  |  |  |  warmwhite  0x00 to 0xFF
#     |  |  |  |  |  |  |  |  blue  0x00 to 0xFF
#     |  |  |  |  |  |  |  green  0x00 to 0xFF
#     |  |  |  |  |  |  red 0x00 to 0xFF
#     |  |  |  |  |  speed: 0x01 = highest 0x1f is lowest
#     |  |  |  |  Mode WW(01), WW+CW(02), RGB(03), RGBW(04), RGBWW(05)
#     |  |  |  preset pattern
#     |  |  off(23)/on(24)
#     |  type
#     msg head
```
(this is the response expected taken from code - note Mode does not define RGBCW accurately for this device and the comments are a little different than the code.) At least maybe update the comments from
`#     |  |  |  |  Mode WW(01), WW+CW(02), RGB(03), RGBW(04), RGBWW(05)`
to
`#     |  |  |  |  Mode(if61) DIM(01), CCT(02), RGB(03), RGBW(04), RGBWW(05)`
and if we can include RGBCW lights to
`#     |  |  |  |  Mode(if61) DIM+RGBCW(01), CCT(02), RGB(03), RGBW(04), RGBWW(05)`

Thank you so much for your help in understanding this one!

**Comment by icemanch** [comment]
Which device do you have?

Have you set it to be in WW+CW mode?

**Comment by Zaacis** [comment]
Hi,

I have RGBCW 7W and RGBCW 9W bulbs. Both seem to work the same.
I have been writing my own module in C# based on the commands documented by vikstrous [here](https://github.com/vikstrous/zengge-lightcontrol):
 
specifically
`31RRGGBBWWXXCC
where:

31 is the ID of the command
RR is red
GG is green
BB is blue
WW is white
XX is whether to use the white value or not
CC is the checksum`

I do not see a way to change the mode. How does one usually set it to be in this mode?

Thank you in advance for your help!

**Comment by icemanch** [comment]
Mode is changed in the app MagicHome which is provided by the company that sales the bulbs.   I only have controllers to test with so I'm not sure if all bulbs support different modes.  On my controllers I can change the mode in the official app and then that will change the value sent in the response for the mode. 

Can you also run the latest version and let me know what it is identifying your bulb as?  

I'll test but I don't think we can just add 01=DIM+RGBW as most of the devices recognize 01 as a single channel device.  This may break some implementations that are depending on the modes to determine the bulb capabilities which would falsely report Dim only bulbs as being able to do RGB.  I've asked the company that makes these bulbs if they can give a more detailed explanation of the responses.  Their API documentation is missing a lot of information.  I suspect we need to focus on the "type" to separate out your bulb and identify it as being RGBCW. 

I thought I had updated the comments but, I'll go through and double check them.

**Comment by Zaacis** [comment]
I do not think this bulb supports different modes. I am using existing firmware on this bulb as I firewalled it from offline access. Another bulb was online recently so it should be running the latest firmware. Both work the same however. I am looking at the newest Magic Home App for iOS(theres one for old phones) and don't see a mode option for this bulb in this app. 
App layout: 
-bottom of the screen colors, cct, functions, mic, music, cinema, camera
-middle of the screen main controls corresponding to selected option.
-top of screen on/off toggle and timer.

From the colors option if I select warm white, cool white, modify the brightness, or change the color, my status pull response will **always** return the same header prefix (as documented earlier) when on which is:
`0x81 0x35 0x23 0x61 0x01 ....`
The final listed 0x01 is the mode which according to the documentation here means WW. I get this response consistently even in CW or RGB mode.

Thank you for your fast response and helpful assistance!

**Comment by icemanch** [comment]
in the app go to the home section which should list the bulbs.  If you press and hold it should give you other options with one of them being "change device type".

The "modes' are documented by the manufactures API.   It's not super great and seems inaccurate and I've asked for clarification but, it's the best we have other then what people have reversed engineered. 

The response to a status request command comes back with the below according to the API documentation.

Position 0 -> 0x81   
Position 1 -> [8 bit Device Name] (We do not currently have a list of devices but, I've asked for it.)
Position 2 -> [8bit on/off] :0x23 = ON, 0x24 = OFF
Position 3 -> [8bit mode] : We have a list of modes.  Basically anything other then 0x61 is a preset pattern like flashing lights or similar.  0x61 = Static.
Position 4 -> [8bit run/pause] :This is where our documentation is pretty lacking.  If it's in mode other then 0x61 it will be 0x20 = play, 0x21 = pause.  There's several other values that are not documented but, typically relate to the mode the bulb is set in as CCT, RGB, RGBW, RGBCW.   Your bulb is reporting that it's in WW or Dim only. 

Everything else is setting colors and speed for transitions.

I've ordered bulbs similar to yours to play around with.  If we can't change the mode then there will have to be some other way to identify or report bulb capabilities.  Is suspect it will end up having something to do with the data in Position 1. 

My bulbs should be here tomorrow and I'll be able to put something together next weekend.

**Comment by Zaacis** [comment]
In the app I tried press and hold and it brings up a menu with two options 1) Add to Group. and 2) Rename. No option to change type on my end.

It's so generous of you to order these bulbs. I inherited mine when they were left by a past roommate hence how I got started on this one.

I am curious where  you got the manufacturers API - I would be interested to have a look the source even though it looks like you document this in programming notes.

**Comment by icemanch** [comment]
Here is the API.   Put in your e-mail and it will e-mail you a download link.

https://westwingx.leadpages.co/flux-developer/

**Comment by icemanch** [comment]
> In the app I tried press and hold and it brings up a menu with two options 1) Add to Group. and 2) Rename. No option to change type on my end.
> 
> It's so generous of you to order these bulbs. I inherited mine when they were left by a past roommate hence how I got started on this one.
> 
> I am curious where you got the manufacturers API - I would be interested to have a look the source even though it looks like you document this in programming notes.

Bulbs came in and I've played with them a bit. I think I've got a fix but, I want to confirm some things with you.

Can you run "flux_led -i IP-ADDRESS"   where "IP-ADDRESS" is the address of the bulb?  Once you've done that please paste the output here.

**Comment by Zaacis** [comment]
Thank you. Here it is:
`>flux_led -i 192.168.9.64
Unknown ID [192.168.9.64] ON  [Warm White: 98% raw state: 129,53,35,97,1,5,0,0,0,250,7,15,15,95,]

>flux_led -i 192.168.9.63
Unknown ID [192.168.9.63] ON  [Warm White: 89% raw state: 129,53,35,97,1,5,0,0,0,228,7,15,15,73,]

>flux_led -i 192.168.9.62
Unknown ID [192.168.9.62] ON  [Warm White: 92% raw state: 129,53,35,97,1,5,0,0,0,235,7,15,15,80,]
`

**Comment by icemanch** [comment]
Still working on this.  It looks like I need to take a combination of the type and mode to determine the capabilities.  I'm finding out that there are a lot of different combinations and I'm trying to find the best way to implement them.  Hoping to have a fix for you be next weekend.

**Comment by Zaacis** [comment]
Thank you so much and I am impressed at how deftly you handled this one.
