### ISSUE TITLE
homebridge-magichome-platform

### ISSUE THREAD

**Issue by janwiesemann** [Danielhiversen/flux_led#81]
Hello there,

as you might know this is used in the homebridge-magichome-platform plugin. This will form a bridge between Apples HomeKit and Magic Home Home controllers. But it seams as if this project is no longer maintained. This is why I'm asking you. Do you have any ideas, why this is happening?

There is an issue, through wich this script uses a lot of cpu time. `ps -aux` reports:

```
python /usr/lib/node_modules/homebridge-magichome-platform/src/flux_led.py 10.0.0.252 -i
```

Restarting node solves the problem but I would like some other fix.

**Comment by icemanch** [comment]
Does the script react the same way if you just run the command flux_led -i ?

**Comment by janwiesemann** [comment]
> Does the script react the same way if you just run the command flux_led -i ?

It does not. It works most of the time. I there is something random going on and I'm, not yet able to reproduce it.

**Comment by icemanch** [comment]
It seems like it's an issue in the homebridge software. I'm glad to look into it further if you're able to reproduce it using just the script.
