### ISSUE TITLE
Travisci.org is not longer available and needs to be changed to travisci.com

### ISSUE THREAD

**Issue by icemanch** [Danielhiversen/flux_led#84]
@Danielhiversen  I tried to move the repo to Travisci.com but, I'm not able to since I don't own the repo.  Can you add it?   I can update the documentation once you do.

**Comment by Danielhiversen** [comment]
I have tried a few times, but the repo is not showing up at travis-ci.com. Will try again later.
You could also use GitHub actions instead

**Comment by icemanch** [comment]
> I have tried a few times, but the repo is not showing up at travis-ci.com. Will try again later. You could also use GitHub actions instead

I'll look into the GitHub actions.
